/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reception_area;

import Admin_area.DBConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author C5
 */
public class Rec_set_appointment extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form Rec_set_appointment
     */
    public Rec_set_appointment() {
        initComponents();
        con=DBConnection.getDBConnection();
        fillcombo();
    }
    public void fillcombo(){
        String sql= "select * from doctor";
        try {
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                ddivision.addItem(rs.getString("division"));
                dname.addItem(rs.getString("name"));
                did.addItem(rs.getString("id"));
                
            }
            
            
            
        } catch (Exception e) {
        }      
        
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        pname = new javax.swing.JTextField();
        paddress = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        ddivision = new javax.swing.JComboBox<>();
        ddate = new com.toedter.calendar.JDateChooser();
        dname = new javax.swing.JComboBox<>();
        did = new javax.swing.JComboBox<>();
        dfee = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pphone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setText("Dhaka City Hospital");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 0, 585, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setText("Set Appointment");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 190, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Disease");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 80, 30));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("Doctor Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("Doctor ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 80, 30));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setText("Date");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 90, 30));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setText("Patient Id");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 100, 30));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setText("Address");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 110, 30));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel12.setText("fee");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 80, 30));
        jPanel1.add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 160, 40));
        jPanel1.add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 160, 40));
        jPanel1.add(paddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 160, 40));

        cancel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        submit.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        submit.setText("submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));

        ddivision.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ddivision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---select---" }));
        ddivision.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ddivisionItemStateChanged(evt);
            }
        });
        ddivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddivisionActionPerformed(evt);
            }
        });
        jPanel1.add(ddivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 160, 40));
        jPanel1.add(ddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 160, 30));

        dname.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        dname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "           " }));
        jPanel1.add(dname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 160, 40));

        did.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        did.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "           " }));
        jPanel1.add(did, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 160, 40));
        jPanel1.add(dfee, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 160, 40));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel13.setText("patient name");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 150, 110, 40));

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel14.setText("Phone");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 80, 30));
        jPanel1.add(pphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
  this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void ddivisionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ddivisionItemStateChanged
String s= ddivision.getSelectedItem().toString();
String sql= "select * from doctor where division='"+s+"'";
        try {             
           PreparedStatement  pst=con.prepareStatement(sql);
           ResultSet    rs=pst.executeQuery();
            while (rs.next()){
                dname.setSelectedItem(rs.getString("name"));
                did.setSelectedItem(rs.getString("id"));
            }
          
        } catch (Exception e) {
        }     
    }//GEN-LAST:event_ddivisionItemStateChanged

    private void ddivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddivisionActionPerformed
//     this code is for loading database value into combobox indivudually;
//        String sql= "select * from patient";
//        try {
//            pst= con.prepareStatement(sql);
//            rs= pst.executeQuery();
//            while(rs.next()){
//                pid.addItem(rs.getString("id"));
//            }
//            
//            
//        } catch (Exception e) {
//        }



    }//GEN-LAST:event_ddivisionActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        
        try {          
            String query = "insert into appointment (doctor_id,doctor_name,division,date,fee,patient_id,Patient_name,address,phone)values (?,?,?,?,?,?,?,?,?)";
            pst = con.prepareStatement(query);

             String docid;
            docid = did.getSelectedItem().toString();
            pst.setString(1, docid);
            
             String name;
            name = dname.getSelectedItem().toString();
            pst.setString(2, name);
            
             String division;
            division = ddivision.getSelectedItem().toString();
            pst.setString(3, division);
            
             SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(ddate.getDate().getTime());
            pst.setString(4, date);
            
             int fee = Integer.parseInt(dfee.getText());
            pst.setInt(5, fee);
            
             int patid = Integer.parseInt(pid.getText());
            pst.setInt(6, patid);
            
            pst.setString(7, pname.getText());
            pst.setString(8, paddress.getText());
            
             int phone = Integer.parseInt(pphone.getText());
            pst.setInt(9, phone);
            
         pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "appointment Successful");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
       
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rec_set_appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rec_set_appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rec_set_appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rec_set_appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rec_set_appointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private com.toedter.calendar.JDateChooser ddate;
    private javax.swing.JComboBox<String> ddivision;
    private javax.swing.JTextField dfee;
    private javax.swing.JComboBox<String> did;
    private javax.swing.JComboBox<String> dname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField paddress;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField pphone;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
