/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Rec_doctor;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Walton
 */
public class Rec_doc_add extends javax.swing.JFrame {
String gender;
    /** Creates new form Rec_doc_add */
    public Rec_doc_add() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        daddress = new javax.swing.JTextField();
        ddegree = new javax.swing.JTextField();
        did = new javax.swing.JTextField();
        dname = new javax.swing.JTextField();
        dphone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        dmale = new javax.swing.JRadioButton();
        dfemale = new javax.swing.JRadioButton();
        ddivision = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("Dhaka City Hospital");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 588, 80));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Doctor Registration");
        jLabel7.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 240, 40));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("Id");
        jLabel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 100, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("Name");
        jLabel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 100, 29));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("Degree");
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 100, 26));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("Address");
        jLabel5.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 100, 29));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setText("Gender");
        jLabel6.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 100, 25));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 51));
        jLabel8.setText("Phone");
        jLabel8.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 100, 33));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 51));
        jLabel9.setText("Division");
        jLabel9.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 100, 27));

        daddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 102)));
        jPanel1.add(daddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 220, 29));

        ddegree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 102)));
        jPanel1.add(ddegree, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 220, 29));

        did.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 102)));
        jPanel1.add(did, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 220, 28));

        dname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 102)));
        jPanel1.add(dname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 220, 30));

        dphone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 102)));
        jPanel1.add(dphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 220, 30));

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton1.setText("back");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 130, 40));

        submit.setBackground(new java.awt.Color(0, 204, 255));
        submit.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        submit.setText("submit");
        submit.setBorder(new javax.swing.border.MatteBorder(null));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 150, 40));

        buttonGroup1.add(dmale);
        dmale.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        dmale.setText("Male");
        jPanel1.add(dmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        buttonGroup1.add(dfemale);
        dfemale.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        dfemale.setText("Female");
        jPanel1.add(dfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, -1, -1));

        ddivision.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ddivision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---select---", "Heart ", "Medicine", "Diabetics", " " }));
        jPanel1.add(ddivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Rec_doc_area rda = new Rec_doc_area();
      rda.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
       Connection con;
       PreparedStatement pst;
        try {
            Class.forName("com.mysql.jdbc.Driver");
          con= DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "123");
            String query= "insert into  doctor (id,name, degree, address, gender,phone,division) values (?,?,?,?,?,?,?)";
             pst = con.prepareStatement(query);
            pst.setString(1, did.getText());
            pst.setString(2,dname.getText());
             pst.setString(3, ddegree.getText());
            pst.setString(4,daddress.getText());
             if (dmale.isSelected()){
                 gender= "male";
             }
             if (dfemale.isSelected()){
                 gender= "female";
             }
             pst.setString(5, gender);                      
            pst.setString(6,dphone.getText());
            String division;
              division=ddivision.getSelectedItem().toString();
               pst.setString(7,division);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "information saved successfully");
        }
         catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, e);
        }
        
        
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rec_doc_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rec_doc_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rec_doc_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rec_doc_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rec_doc_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField daddress;
    private javax.swing.JTextField ddegree;
    private javax.swing.JComboBox<String> ddivision;
    private javax.swing.JRadioButton dfemale;
    private javax.swing.JTextField did;
    private javax.swing.JRadioButton dmale;
    private javax.swing.JTextField dname;
    private javax.swing.JTextField dphone;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables

}
